### ISSUE TITLE
[QUESTION] Verification process takes really long. Caching possible?

### ISSUE THREAD

**Issue by Torsten85** [nickclaw/alexa-ability-express-handler#2]
Hi there,
I've noticed some slow responses from alexa and after digging deeper it boils down to `verifyRequest()`. This method fetches a certificate on every request made from amazon.

Is this really necessary or is it possible to cache that certificate? Fetching does take up to 1.5s which is quite noticeable when you try to have a fluid conversation with alexa ;)

**Comment by nickclaw** [comment]
Great minds think alike https://github.com/nickclaw/alexa-ability-express-handler/blob/03b4a6dca4be445bae4179a37b2f29f8a7fd5eac/src/verifyRequest.js#L101

I'll see what I can do in the next day or two

**Comment by nickclaw** [comment]
@Torsten85 added `cacheSize` and `cacheTime` options to the `verifyRequest` middleware and published as v0.5.0. Check the README for documentation.

Let me know how it works!
